# Generated by Django 4.2.7 on 2026-01-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0018_alter_stripesubscription_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripesubscription',
            name='cancel_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stripesubscription',
            name='current_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stripesubscription',
            name='trial_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
