# Generated by Django 4.2.7 on 2026-01-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
