# Generated by Django 4.2.7 on 2026-01-25 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userfile_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='title'),
        ),
        migrations.CreateModel(
            name='UserNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_status', models.BooleanField(blank=True, default=False)),
                ('last_action', models.DateField(blank=True, null=True)),
                ('current_date_reminder', models.DateField(blank=True, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.account')),
            ],
        ),
    ]
